---
development:
  mongo_host: 
    - name    : localhost
      port    : 27017
  mongo_database: retroard-dev
  
production:
  mongo_host:
    - name    : localhost
      port    : 27017
    - name    : localhost
      port    : 27018
  mongo_database: retroard-production